### ISSUE TITLE
Genomics API autoupdates are failing

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.api#32]
Last successful release on Thursday 4 November; newest data including location fix by @mindoftea hasn't been incorporated.

**Comment by juliamullen** [comment]
Genomics now updated, there were other automatic updates in the past four days but not Genomics so it wasn't a complete hub outage. Still investigating why updates didn't run.

**Comment by juliamullen** [comment]
Looks like we ran into a data error: likely a `true` or `false` on a line by themselves in the data. Here's the error we ran into on Nov 05 from the parser.py file.

>         datum = json.loads(line) 
>         datum['_id'] = datum['accession_id']
>   TypeError: 'bool' object is not subscriptable


json.loads would raise an error if this was e.g., a blank line, but would register a json bool as its bool equivalent, causing this line of code to fail. something to look out for in the future.

Closing as this no longer seems to be an issue in the data.
