### ISSUE TITLE
Using the API for prevalence data

### ISSUE THREAD

**Issue by scc-usc** [outbreak-info/outbreak.api#34]
Hi,
I have been using the APIs as described here for obtaining the prevalence of variants: https://github.com/outbreak-info/outbreak.api/blob/master/web/handlers/genomics/docs.md

However, earlier this month, the APIs as presented in the doc are not working. Is there an updated URL for obtaining data? I am particularly interested in getting the prevalence of all lineages over time per location

Thanks,
Ajitesh

**Comment by nikopech** [comment]
Hi, @scc-usc

Do you have any updates regarding the Genomics API? 
I am really interested in using it but it gives me "HTTP ERROR 401". 

The URL that I am trying is: https://api.outbreak.info/genomics/lineage-mutations?pangolin_lineage=B.1.1.7

Thank you!
Nikolas

**Comment by flaneuse** [comment]
@scc-usc @npechl -- apologies for this dropping off our radar.  As per GISAID's user agreement, our API requires authentication through GISAID credentials. You can access the data underlying outbreak.info via our [R package](https://outbreak-info.github.io/R-outbreak-info/)

**Comment by npechl** [comment]
@scc-usc 
No worries at all. 
Thank you for your reply! 
My problem had been solved a couple of weeks later.
