### ISSUE TITLE
Is it possible to get the sequences

### ISSUE THREAD

**Issue by Juke34** [outbreak-info/outbreak.api#7]
Hi, 

I would like to know if the API allows to retrieve the sequences. Anyone knows?

**Comment by flaneuse** [comment]
Hi @Juke34,

Unfortunately this goes against [GISAID's terms of use](https://www.gisaid.org/registration/terms-of-use/), so we can only provide aggregated statistics.  If you want sequence-level information, you'll have to download them from GISAID yourself. 

If it's helpful, our [data processing pipeline](https://outbreak.info/situation-reports/methods) can be reused to replicate our aggregated stats.

**Comment by Juke34** [comment]
Thank you for your reply request
